server:
  port: ${SERVER_PORT}

spring:
  application:
      name: barointern
  config:
      import: optional:file:.env[.properties]

jwt:
  secret:
    key: ${JWT}

springdoc:
  default-produces-media-type: application/json
  show-login-endpoint: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true


